### ISSUE TITLE
Doesn't support latest ruby versions

### ISSUE THREAD

**Issue by ccavolt** [yanecc/vfox-ruby#1]
`vfox search ruby --no-cache` shows the latest version as 3.2.2, which is incorrect; the latest version is [3.3.2](https://github.com/ruby/ruby/tags). Furthermore, if you try to install a more recent version, it says `Unsupported version: 3.3.2`.

**Comment by yanecc** [comment]
> `vfox search ruby --no-cache` shows the latest version as 3.2.2, which is incorrect; the latest version is [3.3.2](https://github.com/ruby/ruby/tags). Furthermore, if you try to install a more recent version, it says `Unsupported version: 3.3.2`.

To minimize the working requirements of vfox-ruby, the plugin currently uses precompiled packages from conda-forge on Linux and macOS. You could go to [ruby-feedstock](https://github.com/conda-forge/ruby-feedstock/issues) and open an issue to remind them to provide the latest build. Once the latest version is available, the plugin will be updated soon.

**Comment by ccavolt** [comment]
Is minimizing the working requirements really a priority over having up to date versions available? Ruby 3.3 was released over 6 months ago. For comparison, both vfox-erlang and vfox-elixir build from source.

**Comment by yanecc** [comment]
> Is minimizing the working requirements really a priority over having up to date versions available? Ruby 3.3 was released over 6 months ago. For comparison, both vfox-erlang and vfox-elixir build from source.

I have set out to compare the implementation methods of installing the latest Ruby. So the latest minor version should be available for installation soon. Of course, you or anyone who needs compiled versions could supplement the compilation implementation. It's good to have `vfox install ruby@3.3.x -b/--build`. PRs are welcome (of course, I would prefer to see Ruby updated in the conda-forge repository, which would definitely make the installation faster and simpler).

**Comment by ccavolt** [comment]
Thanks for making more up to date versions available, I really appreciate it!
