### ISSUE TITLE
Does not exist (perhaps a typo or a missing channel).

### ISSUE THREAD

**Issue by sljuka** [yanecc/vfox-ruby#3]
Hi @yanecc thank you for making this plugin, the version manager is very handy.
Do you know why this error might be happening when installing Ruby (bit older version)?
```
Davids-MacBook-Pro-2> vfox install ruby@2.6.6
Preinstalling ruby@2.6.6...
Downloading... 100% [========================================================================] (3.9 MB/s)        
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ ruby 2.6.6**  does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
Failed to execute command: /Users/xxx/.version-fox/cache/ruby/v-2.6.6/conda/micromamba create -yqp /Users/xxx/.version-fox/cache/ruby/v-2.6.6/ruby-2.6.6 -r /Users/xxx/.version-fox/cache/ruby/v-2.6.6/conda ruby=2.6.6 -c conda-forge
```

**Comment by yanecc** [comment]
As the error suggests, there are no pre-built packages of some certain versions for macos-aarch64.
And you could view all of the older packages provided [here](https://anaconda.org/conda-forge/ruby/files).
So to use certain versions, you have to compile it, using:
```
vfox install ruby@2.6.6.rb
```
The compilation installation should work for all Ruby versions.
Also, you may want to check all available versions.
https://github.com/yanecc/vfox-ruby/releases/tag/manifest

**Comment by sljuka** [comment]
Aha, awesome, thank you for the explanation!
