### ISSUE TITLE
[Cocoapods] Error while run `pod install`

### ISSUE THREAD

**Issue by hminhman** [yanecc/vfox-ruby#4]
Hi team,
This is a very useful plugin for me, thanks for your efforts. As title, I face some problem while run `pod install`. These are the steps:
- install vfox: `brew install vfox`
- install ruby plugin: `vfox add ruby`
- install a ruby version: `vfox search ruby`  -> then select 3.3.6 (the newest)
- using that version in global: `vfox use -g ruby@3.3.6`
- verify ruby & version to ensure command running correct
- install cocoapods: `gem install cocoapods`
- go to my project then run: `pod install`
- face problem:
"~/.version-fox/temp/1733936400-961/ruby/share/gems/bin/pod: line 6 ~.version-fox/temp/1733936400-961/ruby/share/gems/bin/ruby: No such file or directory"
Then I go to bin of pod and see line 6:
```ruby
=begin
bindir="${0%/*}"
exec "$bindir/ruby" "-x" "$0" "$@"     #=> this is line 6 -> get current pod dir and find ruby bin -> but it's really not found 
=end
```

note: I try to change the code of pod from `"$bindir/ruby"` to `$HOME/.version-fox/shims/ruby` and pod can run. but I used to use rbenv before and I don't need to change this line. So I expected we can do the same thing.

Tell me if I get wrong in any steps.
Thanks vfox & vfox-ruby

**Comment by yanecc** [comment]
When you run `vfox use -g ruby@3.3.6`, vfox will store the ruby shim in the `~/.version-fox/shims/` directory.  
At the same time, it will mount the following two directories to the PATH environment variable:
- `~/.version-fox/cache/ruby/v-3.3.6/ruby-3.3.6/bin`
- `~/.version-fox/cache/ruby/v-3.3.6/ruby-3.3.6/share/gems/bin`

These two directories are the default paths for storing the ruby executable and gems, respectively.  
After you run `gem install cocoapods`, the pod script is added to the second directory. You need to run `vfox use -g ruby@3.3.6` again to store the pod shim in the `~/.version-fox/shims/` directory.

Obviously, whether through vfox mounting to the cache directory or a temporary directory, the ruby and pod programs are located in different relative paths, which leads to the issue you are currently encountering.  
Therefore, you need to add the `~/.version-fox/shims/` directory to the beginning of the PATH environment variable:

```bash
export PATH="$HOME/.version-fox/shims:$PATH"
```

I hope this helps.

> Of course, I understand that this is a bit cumbersome. Ideally, vfox should provide a way to accomplish all of the above in one command. In any case, vfox still has many shortcomings and requires a lot of heavy development work to be practical for daily use.

**Comment by hminhman** [comment]
Thanks for your answer, I will try somethings and update later. I think if I extends "$HOME/.version-fox/shims:$PATH" in .zshrc it's may work but not sure with this idea. Just let me try and I will explain later. thank you.
